spring:
  h2:
    console:
      enabled: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:simblog;NON_KEYWORDS=USER
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
   # properties:
   #   hibernate:
   #     format_sql: true
   #     show_sql: true
   #     use_sql_comments: true

  data:
    web:
      pageable:
        one-indexed-parameters: true
        max-page-size: 2000
        default-page-size: 20
#  sql:
#    init:
#      mode: never
#      data-locations: classpath:sql/**sql
#        default-page-size: 5

simblog:
  jwt-key: "lw66aemS5Fr4J7GXkzRP4ZxcHBpAKY0oZN5ncuoFqhY="