### コンテンツ作成

POST http://localhost:8080/posts
Content-Type: application/json

{
  "title": "タイトルです。",
  "content": "コンテンツです。"
}

### コンテンツ削除

DELETE http://localhost:8080/posts/1
Content-Type: application/json